#!/bin/bash

source "$(dirname $0)/fn"

if [ "$#" -lt 1 ]; then
	echo ERROR: Please specify backup ID which is one from below:
	find $CFGDIR -maxdepth 1 -type f -exec basename {} \;
	exit 1
fi

bak_id="$1"

if [[ ! -f "$CFGDIR/$bak_id" ]]; then
	echo ERROR: Backup ID $bak_id does not exists!
	exit 1
fi

source "$CFGDIR/$bak_id"

bak_file=$(date "+$bak_arc.tar.gz")
info "ARCHIVING $bak_file ..."
tar -czpf $bak_file -C $bak_path .
 
info "UPLOADING TO SFTP $bak_sftp_host ..."
#sftp $bak_sftp_options -oStrictHostKeyChecking=no -P "$bak_sftp_port" $bak_sftp_user@$bak_sftp_host 1>/dev/null 2>/dev/null <<< ```
#	echo put $bak_file $bak_sftp_path/
#	echo exit 
#```
scp $bak_sftp_options -oStrictHostKeyChecking=no -P "$bak_sftp_port" $bak_file $bak_sftp_user@$bak_sftp_host:$bak_sftp_path/

rm $bak_file

