#!/bin/bash

source "$(dirname $0)/fn"

if [ "$#" -lt 1 ]; then
	echo ERROR: Please specify backup ID which is one from below:
	find $CFGDIR -maxdepth 1 -type f -exec basename {} \;
	exit 1
fi

BAK_ID="$1"

if [[ ! -f "$CFGDIR/$BAK_ID" ]]; then
	echo ERROR: Backup ID $BAK_ID does not exists!
	exit 1
fi

source "$CFGDIR/$BAK_ID"

BAK_FILE=$(date "+$BAK_ARC.tar.gz")
info "Archiving $BAK_FILE ..."
tar -czpf $BAK_FILE -C $BAK_PATH .
 
info "Uploading to SCP server $BAK_SCP_USER@$BAK_SCP_HOST:$BAK_SCP_PORT ..."
SCP_OPTIONS="-oStrictHostKeyChecking=no"
if [[ ! -z "$BAK_SCP_PKEY" ]]; then
	SCP_OPTIONS="$SCP_OPTIONS -i $BAK_SCP_PKEY"
fi
scp $SCP_OPTIONS -P $BAK_SCP_PORT $BAK_FILE $BAK_SCP_USER@$BAK_SCP_HOST:$BAK_SCP_PATH/

rm $BAK_FILE
info Completed.
