#!/bin/bash

source "$(dirname $0)/fn"

if [ "$#" -lt 1 ]; then
	echo ERROR: Please specify backup ID which is one from below:
	find $CFGDIR -maxdepth 1 -type f -exec basename {} \;
	exit 1
fi

bak_id="$1"

if [[ ! -f "$CFGDIR/$bak_id" ]]; then
	echo ERROR: Backup ID $bak_id does not exists!
	exit 1
fi

source "$CFGDIR/$bak_id"

bak_file=$(date "+$bak_arc.tar.gz")
info "ARCHIVING $bak_file ..."
tar -czpf $bak_file -C $bak_path .
 
info "UPLOADING TO SCP $bak_scp_user@$bak_scp_host:$bak_scp_port ..."
scp_options="-oStrictHostKeyChecking=no"
if [[ ! -z "$bak_scp_pkey" ]]; then
	scp_options="$scp_options -i $bak_scp_pkey"
fi
scp $scp_options -P $bak_scp_port $bak_file $bak_scp_user@$bak_scp_host:$bak_scp_path/

rm $bak_file

